---
title: Murray Lampert
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  team-member:
    title: team-member
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    featured-image: ''
    excerpt: ''
    author: ''
url: https://murray-lampert.netlify.com # change before moving site to Netlify servers
baseurl:
email: info@murraylampert.com
description: Murray Lampert design, build, and home remodel services in San Diego. Proud to be San Diego's top home design build remodel contractor since 1975.
logo: /uploads/assets/images/logo.jpg
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
permalinks: pretty
include:
- _redirects
plugins:
- jekyll-paginate
paginate: 4
paginate_path: blog/page:num
