---
title: Murray Lampert
timezone: UTC
collections:
  featured-projects:
    title: Featured Projects
    output: true
    permalink: "/:collection/:path/"
  job-openings:
    title: Job Openings
    output: false
  landing:
    title: Landing Pages
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: Posts
    output: true
  project-galleries:
    title: Project Galleries
    output: true
  service-locations:
    title: Service Locations
    output: true
    permalink: "/:collection/:path/"
  team-member:
    title: Team Members
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:title/"
    featured-image: ''
    excerpt: ''
    author: ''
- scope:
    path: ''
    type: featured-projects
  values:
    layout: featured-project
    client: ''
    location: ''
    project-date: ''
    featured-video: ''
    featured-images: ''
    excerpt: ''
- scope:
    path: ''
    type: job-openings
  values:
    job-description: ''
    application-url: ''
url: https://murraylampert.com
baseurl:
email: info@murraylampert.com
description: Murray Lampert design, build, and home remodel services in San Diego.
  Proud to be San Diego's top home design build remodel contractor since 1975.
logo: "/uploads/assets/images/logo.jpg"
markdown: kramdown
permalink: pretty
exclude: []
include:
- _redirects
plugins:
- jekyll-paginate
- jekyll-sitemap
paginate: 4
paginate_path: blog/page:num
