---
title: Murray Lampert

description: Murray Lampert design, build, and home remodel services in San Diego. Proud to be San Diego's top home design build remodel contractor since 1975.

url: https://murraylampert.com

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

markdown: kramdown

kramdown:
  auto_ids: false

permalink: pretty

include:
- _redirects

exclude: []

plugins:
- jekyll-paginate
- jekyll-sitemap

paginate: 4
paginate_path: blog/page:num
