---
title: Murray Lampert
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: ''
    excerpt: ''
    author: ''
url:
baseurl:
email: info@murraylampert.com
description: Murray Lampert specializes in design, build, and remodel services in San Diego. Proud to be San Diego's top design build remodel contractor since 1975.
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
permalinks: pretty
include:
- _redirects
plugins:
- jekyll-paginate
paginate: 4
paginate_path: blog/page:num
