---
title: Murray Lampert
timezone: UTC
collections:
  featured-projects:
    title: Featured Projects
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  team-member:
    title: Team Members
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    featured-image: ''
    excerpt: ''
    author: ''
- scope:
    path: ''
    type: featured-projects
  values:
    layout: featured-project
    client: ''
    location: ''
    project-date: ''
    featured-video: ''
    featured-images: ''
    excerpt: ''
url: https://murray-lampert.netlify.com
baseurl:
email: info@murraylampert.com
description: Murray Lampert design, build, and home remodel services in San Diego.
  Proud to be San Diego's top home design build remodel contractor since 1975.
logo: "/uploads/assets/images/logo.jpg"
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
permalinks: pretty
include:
- _redirects
plugins:
- jekyll-paginate
paginate: 4
paginate_path: blog/page:num
