---
---

---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: documents
  templates:
  - page-builder
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - blog-post
- type: directory
  path: _featured-projects
  label: Featured Projects
  create: documents
  match: "**/*"
  templates:
  - featured-project
- type: directory
  path: _service-locations
  label: Service Locations
  create: documents
  match: "**/*"
  templates:
  - page-builder
upload_dir: murray-lampert/version3
public_path: https://res.cloudinary.com/zheisey/image/upload/f_auto,q_auto,dpr_auto
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
